name: Object Detection Workflow

on:
  push:
    branches:
      - main  # Define the branch to trigger the workflow

jobs:
  setup-nvidia-toolkit:
    runs-on: ubuntu-latest
    steps:
      - name: Install NVIDIA Container Toolkit
        run: |
          curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
          && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
            sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
            sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list \
          && sudo apt-get update \
          && sudo apt-get install -y nvidia-container-toolkit \
          && sudo nvidia-ctk runtime configure --runtime=docker \
          && sudo systemctl restart docker

  pull-tensorflow-images:
    runs-on: ubuntu-latest
    needs: setup-nvidia-toolkit
    steps:
      - name: Pull TensorFlow Docker Images
        run: |
          docker pull tensorflow/tensorflow
          docker pull tensorflow/tensorflow:devel-gpu
          docker pull tensorflow/tensorflow:latest-gpu-jupyter

  build:
    runs-on: ubuntu-latest  # Specify the runner OS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Checkout the repository content

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment

      - name: Install dependencies
        working-directory: supervised_learning/object_detection  # Set working directory
        run: |
          pip install -r requirements.txt  # Install Python dependencies
          # Additional setup if needed

      - name: Build Docker Image
        working-directory: supervised_learning/object_detection  # Set working directory
        run: |
          docker build -t my_tensorflow_app .  # Build the Docker image
          # Additional steps as needed for image setup

      - name: Run Object Detection
        run: |
          docker run -it --rm --device=/dev/video0 my_tensorflow_app
          # Command to run object detection script within the container
